### ISSUE TITLE
IndexClientError: unable to connect to the index server at 127.0.0.1:6080

### ISSUE THREAD

**Issue by gaochengcai** [acoustid/acoustid-server#38]
Call /api/ws/v2/lookup
results in this error:

`[ERROR] acoustid.data.fingerprint - Index search error
Traceback (most recent call last):
  File "/home/ubuntu/VideoFingerprint/acoustid-server/acoustid/data/fingerprint.py", line 123, in search
    matches = self._search_index(fp, length)

  File "/home/ubuntu/VideoFingerprint/acoustid-server/acoustid/data/fingerprint.py", line 87, in _search_index
    with closing(self.idx.connect()) as idx:

  File "/home/ubuntu/VideoFingerprint/acoustid-server/acoustid/indexclient.py", line 208, in connect
    client = IndexClient(**self.args)

  File "/home/ubuntu/VideoFingerprint/acoustid-server/acoustid/indexclient.py", line 39, in __init__
    self._connect()

  File "/home/ubuntu/VideoFingerprint/acoustid-server/acoustid/indexclient.py", line 56, in _connect
    raise IndexClientError('unable to connect to the index server at %s:%s' % (self.host, self.port))

IndexClientError: unable to connect to the index server at 127.0.0.1:6080`

I don't understand index server.

thanks~

**Comment by lalinsky** [comment]
You need to have this running https://github.com/acoustid/acoustid-index

**Comment by gaochengcai** [comment]
thank you~
